name: habit_tracker_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  uuid: ^4.1.0
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.3
  equatable: ^2.0.5
  test: ^1.24.3
  google_fonts: ^6.1.0
  date_picker_timeline: ^1.2.5
  flutter_riverpod: ^2.4.9
  hooks_riverpod: ^2.4.9
  flutter_hooks: ^0.20.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_iconpicker: ^3.2.4
  syncfusion_flutter_charts: ^24.1.41
  restart_app: ^1.2.1

flutter_native_splash:
  color: "#03001C"
  image: assets/images/habit-splash.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
